/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check API and database health.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assets
         * @description List assets with optional filtering.
         */
        get: operations["list_assets_api_v1_assets_get"];
        put?: never;
        /**
         * Create Asset
         * @description Create a new asset.
         */
        post: operations["create_asset_api_v1_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Asset
         * @description Get a single asset by UID.
         */
        get: operations["get_asset_api_v1_assets__uid__get"];
        /**
         * Update Asset
         * @description Update an existing asset.
         */
        put: operations["update_asset_api_v1_assets__uid__put"];
        post?: never;
        /**
         * Delete Asset
         * @description Delete an asset.
         */
        delete: operations["delete_asset_api_v1_assets__uid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Actors
         * @description List actors with optional filtering.
         */
        get: operations["list_actors_api_v1_actors_get"];
        put?: never;
        /**
         * Create Actor
         * @description Create a new actor (person or group).
         */
        post: operations["create_actor_api_v1_actors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actors/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Actor
         * @description Get a single actor by UID.
         */
        get: operations["get_actor_api_v1_actors__uid__get"];
        /**
         * Update Actor
         * @description Update an existing actor.
         */
        put: operations["update_actor_api_v1_actors__uid__put"];
        post?: never;
        /**
         * Delete Actor
         * @description Delete an actor.
         */
        delete: operations["delete_actor_api_v1_actors__uid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Relations
         * @description List relations with optional filtering.
         */
        get: operations["list_relations_api_v1_relations_get"];
        put?: never;
        /**
         * Create Relation
         * @description Create a new relation between two nodes.
         */
        post: operations["create_relation_api_v1_relations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/relations/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Relation
         * @description Get a single relation by UID.
         */
        get: operations["get_relation_api_v1_relations__uid__get"];
        put?: never;
        post?: never;
        /**
         * Delete Relation
         * @description Delete a relation.
         */
        delete: operations["delete_relation_api_v1_relations__uid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description List events with optional filtering.
         */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description Get a single event by UID.
         */
        get: operations["get_event_api_v1_events__uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rules
         * @description List rules with optional filtering.
         */
        get: operations["list_rules_api_v1_rules_get"];
        put?: never;
        /**
         * Create Rule
         * @description Create a new rule.
         */
        post: operations["create_rule_api_v1_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/for-asset/{asset_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rules For Asset
         * @description List all rules applied to an asset, with enforcement context per rule.
         */
        get: operations["list_rules_for_asset_api_v1_rules_for_asset__asset_uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rule
         * @description Get a single rule by UID.
         */
        get: operations["get_rule_api_v1_rules__uid__get"];
        /**
         * Update Rule
         * @description Update an existing rule.
         */
        put: operations["update_rule_api_v1_rules__uid__put"];
        post?: never;
        /**
         * Delete Rule
         * @description Delete a rule (and all APPLIES_TO relations through DETACH DELETE).
         */
        delete: operations["delete_rule_api_v1_rules__uid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Search across assets, actors, rules and schema nodes.
         *
         *     Returns a flat `items` list where each entry is tagged with `kind`
         *     (asset / container / field / actor / rule). Empty queries return
         *     an empty list — the UI treats empty search as "show nothing yet".
         */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph Map
         * @description Return the data-landscape map at the requested LOD tier.
         */
        get: operations["get_graph_map_api_v1_graph_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plugins
         * @description Return all registered plugin manifests for UI auto-discovery.
         */
        get: operations["list_plugins_api_v1_plugins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins/{slug}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Plugin
         * @description Run a plugin. Multipart inputs are parsed against the manifest.
         *
         *     - SummaryResult → returned as JSON
         *     - DownloadResult → streamed back with an attachment Content-Disposition
         */
        post: operations["run_plugin_api_v1_plugins__slug__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorCreate
         * @description Request body for creating an actor.
         */
        ActorCreate: {
            /**
             * Uid
             * @description Optional client-supplied UID for idempotent creation. Auto-generated if not provided.
             */
            uid?: string | null;
            type: components["schemas"]["ActorType"];
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Verified
             * @default true
             */
            verified: boolean;
            /** Discovered By */
            discovered_by?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * ActorHit
         * @description A person or team that matched.
         */
        ActorHit: {
            /**
             * Kind
             * @default actor
             * @constant
             */
            kind: "actor";
            /** Uid */
            uid: string;
            /** Name */
            name: string;
            type: components["schemas"]["ActorType"];
            /** Email */
            email?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ActorListResponse
         * @description Response model for listing actors.
         */
        ActorListResponse: {
            /** Items */
            items: components["schemas"]["ActorResponse"][];
            /** Total */
            total: number;
        };
        /**
         * ActorResponse
         * @description Response model for a single actor.
         */
        ActorResponse: {
            /** Uid */
            uid: string;
            type: components["schemas"]["ActorType"];
            /** Name */
            name: string;
            /** Email */
            email: string | null;
            /** Description */
            description: string | null;
            /** Verified */
            verified: boolean;
            /** Discovered By */
            discovered_by: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ActorType
         * @description Valid actor types.
         * @enum {string}
         */
        ActorType: "person" | "group";
        /**
         * ActorUpdate
         * @description Request body for updating an actor.
         */
        ActorUpdate: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Description */
            description?: string | null;
            /** Verified */
            verified?: boolean | null;
            /** Discovered By */
            discovered_by?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * AppliedRule
         * @description Rule + its per-asset APPLIES_TO context (enforcement, field_path, note).
         */
        AppliedRule: {
            rule: components["schemas"]["RuleResponse"];
            /** Relation Uid */
            relation_uid: string;
            /** Enforcement */
            enforcement?: string | null;
            /** Field Path */
            field_path?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Properties
             * @default {}
             */
            properties: {
                [key: string]: unknown;
            };
        };
        /**
         * AppliedRulesResponse
         * @description List of rules applied to one asset, with enforcement context per rule.
         */
        AppliedRulesResponse: {
            /** Items */
            items: components["schemas"]["AppliedRule"][];
            /** Total */
            total: number;
        };
        /**
         * AssetCreate
         * @description Request body for creating an asset.
         */
        AssetCreate: {
            /**
             * Uid
             * @description Optional client-supplied UID for idempotent creation. Auto-generated if not provided.
             */
            uid?: string | null;
            type: components["schemas"]["AssetType"];
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** @default active */
            status: components["schemas"]["AssetStatus"];
            /**
             * Verified
             * @default true
             */
            verified: boolean;
            /** Discovered By */
            discovered_by?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * AssetHit
         * @description An asset that matched the query.
         */
        AssetHit: {
            /**
             * Kind
             * @default asset
             * @constant
             */
            kind: "asset";
            /** Uid */
            uid: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            type: components["schemas"]["AssetType"];
            status: components["schemas"]["AssetStatus"];
        };
        /**
         * AssetListResponse
         * @description Response model for listing assets.
         */
        AssetListResponse: {
            /** Items */
            items: components["schemas"]["AssetResponse"][];
            /** Total */
            total: number;
        };
        /**
         * AssetResponse
         * @description Response model for a single asset.
         */
        AssetResponse: {
            /** Uid */
            uid: string;
            type: components["schemas"]["AssetType"];
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Location */
            location: string | null;
            status: components["schemas"]["AssetStatus"];
            /** Verified */
            verified: boolean;
            /** Discovered By */
            discovered_by: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AssetStatus
         * @description Asset lifecycle status.
         * @enum {string}
         */
        AssetStatus: "active" | "deprecated" | "draft";
        /**
         * AssetType
         * @description Valid asset types.
         * @enum {string}
         */
        AssetType: "dataset" | "report" | "process" | "system";
        /**
         * AssetUpdate
         * @description Request body for updating an asset.
         */
        AssetUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            status?: components["schemas"]["AssetStatus"] | null;
            /** Verified */
            verified?: boolean | null;
            /** Discovered By */
            discovered_by?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ContainerHit
         * @description A schema container (table, sheet, section, …) that matched.
         */
        ContainerHit: {
            /**
             * Kind
             * @default container
             * @constant
             */
            kind: "container";
            /** Asset Uid */
            asset_uid: string;
            /** Asset Name */
            asset_name: string;
            /** Name */
            name: string;
            /**
             * Path
             * @description Slash-joined path from asset root
             */
            path: string;
            /** Container Type */
            container_type?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * EntityType
         * @description Types of entities that can be tracked.
         * @enum {string}
         */
        EntityType: "asset" | "actor" | "relation" | "rule";
        /**
         * EventAction
         * @description Types of audit actions.
         * @enum {string}
         */
        EventAction: "created" | "updated" | "deleted";
        /**
         * EventListResponse
         * @description Response model for listing events.
         */
        EventListResponse: {
            /** Items */
            items: components["schemas"]["EventResponse"][];
            /** Total */
            total: number;
        };
        /**
         * EventResponse
         * @description Response model for a single event.
         */
        EventResponse: {
            /** Uid */
            uid: string;
            action: components["schemas"]["EventAction"];
            entity_type: components["schemas"]["EntityType"];
            /** Entity Uid */
            entity_uid: string;
            /** Actor Uid */
            actor_uid: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Changes */
            changes?: {
                [key: string]: unknown;
            };
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * FieldHit
         * @description A schema field (column, measure, …) that matched.
         */
        FieldHit: {
            /**
             * Kind
             * @default field
             * @constant
             */
            kind: "field";
            /** Asset Uid */
            asset_uid: string;
            /** Asset Name */
            asset_name: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Data Type */
            data_type?: string | null;
            /**
             * Pii
             * @default false
             */
            pii: boolean;
            /** Description */
            description?: string | null;
        };
        /**
         * GraphEdge
         * @description A relation between two map nodes. Both endpoints are always visible
         *     at their declared `lod`; edges inherit the higher of the two tiers.
         */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Type
             * @description Relation type: owns, uses, feeds, …
             */
            type: string;
            lod: components["schemas"]["LodTier"];
        };
        /**
         * GraphMapResponse
         * @description The data-landscape map at a given LOD ceiling.
         */
        GraphMapResponse: {
            lod: components["schemas"]["LodTier"];
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /**
             * Bounds
             * @description Layout bounding box in 3D: (x_min, y_min, z_min, x_max, y_max, z_max).
             */
            bounds: [
                number,
                number,
                number,
                number,
                number,
                number
            ];
        };
        /**
         * GraphNode
         * @description A node on the map, with its pre-computed world coordinates.
         *
         *     Coordinates are in a 3D space: `(x, y)` is the galactic plane,
         *     `z` is the layer offset so LOD tiers visually stack (tier 0 sits on
         *     `z≈0`, tier 1 spreads in a thin shell around it). A 2D renderer can
         *     ignore `z` entirely.
         */
        GraphNode: {
            /**
             * Id
             * @description Unique id (entity UID)
             */
            id: string;
            /**
             * Label
             * @description Display label
             */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "asset" | "actor" | "rule";
            /**
             * Subtype
             * @description Asset type, actor type, or rule severity — drives node color
             */
            subtype: string;
            /** @description Lowest LOD tier at which this node becomes visible */
            lod: components["schemas"]["LodTier"];
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Z
             * @description Depth coordinate (0 for 2D layouts)
             * @default 0
             */
            z: number;
            /**
             * Degree
             * @description Relation count — drives hub glow on the 3D renderer
             * @default 0
             */
            degree: number;
            /**
             * Size
             * @description Render size hint (degree-based, already normalized)
             */
            size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InputSpec
         * @description One input the plugin expects in `run()`.
         *
         *     Drives both the API (multipart parsing) and the UI (form rendering).
         */
        InputSpec: {
            /** Name */
            name: string;
            type: components["schemas"]["InputType"];
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
            /** Accept */
            accept?: string | null;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Default */
            default?: unknown;
        };
        /**
         * InputType
         * @enum {string}
         */
        InputType: "file" | "string" | "boolean";
        /**
         * LodTier
         * @description Level-of-detail tiers.
         *
         *     `tier 0` is the "max zoom out architecture view" — only top-level
         *     entities (systems + teams). `tier 1` adds every first-class node
         *     (assets, people, rules). Future `tier 2` would add schema nodes
         *     (containers + fields).
         * @enum {integer}
         */
        LodTier: 0 | 1;
        /**
         * PluginCapability
         * @description What kind of action the plugin performs.
         *
         *     - IMPORT: takes inputs (often a file), pushes assets/actors/relations to the API,
         *       returns a JSON summary that the UI renders as stat cards + a sample list.
         *     - EXPORT: produces a file download (no inputs needed in v0.1).
         * @enum {string}
         */
        PluginCapability: "import" | "export";
        /** PluginListResponse */
        PluginListResponse: {
            /** Plugins */
            plugins: components["schemas"]["PluginManifest"][];
        };
        /**
         * PluginManifest
         * @description Self-description of a plugin. Returned to the UI for auto-rendering.
         */
        PluginManifest: {
            /**
             * Slug
             * @description URL-safe identifier — must be unique across plugins
             */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Icon
             * @default 🧩
             */
            icon: string;
            /**
             * Version
             * @default 0.0.0
             */
            version: string;
            capability: components["schemas"]["PluginCapability"];
            /** Inputs */
            inputs?: components["schemas"]["InputSpec"][];
            /** Review Link */
            review_link?: string | null;
        };
        /**
         * RelationCreate
         * @description Request body for creating a relation.
         */
        RelationCreate: {
            /**
             * Uid
             * @description Optional client-supplied UID for idempotent creation. Auto-generated if not provided.
             */
            uid?: string | null;
            /**
             * From Uid
             * @description UID of the source node
             */
            from_uid: string;
            /**
             * To Uid
             * @description UID of the target node
             */
            to_uid: string;
            type: components["schemas"]["RelationType"];
            /**
             * Verified
             * @default true
             */
            verified: boolean;
            /** Discovered By */
            discovered_by?: string | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /**
         * RelationListResponse
         * @description Response model for listing relations.
         */
        RelationListResponse: {
            /** Items */
            items: components["schemas"]["RelationResponse"][];
            /** Total */
            total: number;
        };
        /**
         * RelationResponse
         * @description Response model for a single relation.
         */
        RelationResponse: {
            /** Uid */
            uid: string;
            /** From Uid */
            from_uid: string;
            /** To Uid */
            to_uid: string;
            type: components["schemas"]["RelationType"];
            /** Verified */
            verified: boolean;
            /** Discovered By */
            discovered_by: string | null;
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RelationType
         * @description Valid relation types.
         *
         *     Data-flow lineage is asset-only: the single FEEDS edge covers
         *     upstream → downstream flow between any two assets (including
         *     processes, which participate as plain asset nodes). We intentionally
         *     do not carry PRODUCES/CONSUMES or DERIVED_FROM so the same data flow
         *     never has two parallel encodings.
         * @enum {string}
         */
        RelationType: "owns" | "uses" | "feeds" | "contains" | "member_of" | "applies_to";
        /**
         * RuleCreate
         * @description Request body for creating a rule.
         */
        RuleCreate: {
            /**
             * Uid
             * @description Optional client-supplied UID for idempotent creation. Auto-generated if not provided.
             */
            uid?: string | null;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** @default warning */
            severity: components["schemas"]["RuleSeverity"];
            /** Category */
            category?: string | null;
            /**
             * Verified
             * @default true
             */
            verified: boolean;
            /** Discovered By */
            discovered_by?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * RuleHit
         * @description A data-quality rule that matched.
         */
        RuleHit: {
            /**
             * Kind
             * @default rule
             * @constant
             */
            kind: "rule";
            /** Uid */
            uid: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            severity: components["schemas"]["RuleSeverity"];
            /** Category */
            category?: string | null;
        };
        /**
         * RuleListResponse
         * @description Response model for listing rules.
         */
        RuleListResponse: {
            /** Items */
            items: components["schemas"]["RuleResponse"][];
            /** Total */
            total: number;
        };
        /**
         * RuleResponse
         * @description Response model for a single rule.
         */
        RuleResponse: {
            /** Uid */
            uid: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            severity: components["schemas"]["RuleSeverity"];
            /** Category */
            category: string | null;
            /** Verified */
            verified: boolean;
            /** Discovered By */
            discovered_by: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RuleSeverity
         * @description How bad a rule violation is, inherent to the kind of rule.
         * @enum {string}
         */
        RuleSeverity: "info" | "warning" | "critical";
        /**
         * RuleUpdate
         * @description Request body for updating a rule. All fields optional.
         */
        RuleUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            severity?: components["schemas"]["RuleSeverity"] | null;
            /** Category */
            category?: string | null;
            /** Verified */
            verified?: boolean | null;
            /** Discovered By */
            discovered_by?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SearchResponse
         * @description Cross-entity search results.
         */
        SearchResponse: {
            /** Items */
            items: (components["schemas"]["AssetHit"] | components["schemas"]["ContainerHit"] | components["schemas"]["FieldHit"] | components["schemas"]["ActorHit"] | components["schemas"]["RuleHit"])[];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_assets_api_v1_assets_get: {
        parameters: {
            query?: {
                /** @description Filter by asset type */
                type?: components["schemas"]["AssetType"] | null;
                /** @description Max items to return */
                limit?: number;
                /** @description Number of items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_asset_api_v1_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_asset_api_v1_assets__uid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_asset_api_v1_assets__uid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_actors_api_v1_actors_get: {
        parameters: {
            query?: {
                /** @description Filter by actor type */
                type?: components["schemas"]["ActorType"] | null;
                /** @description Max items to return */
                limit?: number;
                /** @description Number of items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_actor_api_v1_actors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_actor_api_v1_actors__uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_actor_api_v1_actors__uid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_actor_api_v1_actors__uid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relations_api_v1_relations_get: {
        parameters: {
            query?: {
                /** @description Filter by relation type */
                type?: components["schemas"]["RelationType"] | null;
                /** @description Filter by source node UID */
                from_uid?: string | null;
                /** @description Filter by target node UID */
                to_uid?: string | null;
                /** @description Max items to return */
                limit?: number;
                /** @description Number of items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relation_api_v1_relations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relation_api_v1_relations__uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relation_api_v1_relations__uid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                /** @description Filter by entity type */
                entity_type?: components["schemas"]["EntityType"] | null;
                /** @description Filter by entity UID */
                entity_uid?: string | null;
                /** @description Filter by action */
                action?: components["schemas"]["EventAction"] | null;
                /** @description Max items to return */
                limit?: number;
                /** @description Number of items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_rules_get: {
        parameters: {
            query?: {
                /** @description Filter by category */
                category?: string | null;
                /** @description Filter by severity */
                severity?: components["schemas"]["RuleSeverity"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_v1_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_for_asset_api_v1_rules_for_asset__asset_uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppliedRulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_api_v1_rules__uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_v1_rules__uid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_v1_rules__uid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query?: {
                /** @description Free-text query */
                q?: string;
                /** @description Max items to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_map_api_v1_graph_map_get: {
        parameters: {
            query?: {
                /** @description Level-of-detail ceiling. 0 = overview (systems + teams only); 1 = full entity map (+ datasets, reports, processes, people, rules). */
                lod?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphMapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plugins_api_v1_plugins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginListResponse"];
                };
            };
        };
    };
    run_plugin_api_v1_plugins__slug__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
